insert into ExampleDb.bank_code (code, description, created_at)
values
('MBAPP', 'Ung dung MobileBanking', NOW()),
('VNPAYQR', 'VNPAYQR', NOW()),
('VNBANK', 'LOCAL BANK', NOW()),
('IB', 'INTERNET BANKING', NOW()),
('ATM', 'ATM CARD', NOW()),
('INTCARD', 'INTERNATIONAL CARD', NOW()),
('VISA', 'VISA', NOW()),
('MASTERCARD', 'MASTERCARD', NOW()),
('JCB', 'JCB', NOW()),
('UPI', 'UPI', NOW()),
('VIB', 'VIB', NOW()),
('VIETCAPITALBANK', 'VIETCAPITALBANK', NOW()),
('SCB', 'Ngan hang SCB', NOW()),
('NCB', 'Ngan hang NCB', NOW()),
('SACOMBANK', 'Ngan hang SacomBank', NOW()),
('EXIMBANK', 'Ngan hang EximBank', NOW()),
('MSBANK', 'Ngan hang MSBANK', NOW()),
('NAMABANK', 'Ngan hang NamABank', NOW()),
('VNMART', 'Vi dien tu VnMart', NOW()),
('VIETINBANK', 'Ngan hang Vietinbank', NOW()),
('VIETCOMBANK', 'Ngan hang VCB', NOW()),
('HDBANK', 'Ngan hang HDBank', NOW()),
('DONGABANK', 'Ngan hang Dong A', NOW()),
('TPBANK', 'Ngan hang TPBank', NOW()),
('OJB', 'Ngan hang OceanBank', NOW()),
('BIDV', 'Ngan hang BIDV', NOW()),
('TECHCOMBANK', 'Ngan hang Techcombank', NOW()),
('VPBANK', 'Ngan hang VPBank', NOW()),
('AGRIBANK', 'Ngan hang Agribank', NOW()),
('MBBANK', 'Ngan hang MBBank', NOW()),
('ACB', 'Ngan hang ACB', NOW()),
('OCB', 'Ngan hang OCB', NOW()),
('IVB', 'Ngan hang IVB', NOW()),
('SHB', 'Ngan hang SHB', NOW());