INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (1, 'Booking.Approve.Meeting', 'Can approve meeting', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (2, 'Booking.Confirm.Met', 'Can confirm guest met motel', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (3, 'Booking.Create.Meeting', 'Can create meeting', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (4, 'Booking.View.All.Booked', 'Can view all meeting of guest', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (5, 'Booking.View.All.Personal', 'Can view all meeting of host', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (6, 'Bookmark.Create', 'Can create a bookmark', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (7, 'Bookmark.Remove', 'Can remove a bookmark', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (8, 'Bookmark.View', 'Can view bookmarked post', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (9, 'ConfigSetting.Update', 'Can update config setting', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (10, 'ConfigSetting.View.All', 'Can view all config setting', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (11, 'ConfigSetting.View.One', 'Can view one config setting', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (12, 'FreeTime.Create', 'Can create free time', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (13, 'FreeTime.View.All', 'Can view all free time', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (14, 'Notification.Update', 'Can update notification', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (15, 'Notification.View.All', 'Can view all notification', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (16, 'Payment.View.All.History', 'Can view all payment history in system', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (17, 'Payment.View.All.History.Personal', 'Can view personal payment history', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (18, 'Permission.Create', 'Can add new permission for role', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (19, 'Permission.Remove', 'Can remove permission from role', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (20, 'Permission.View', 'Can view permission of a role', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (21, 'Post.Check.Duplicate.Uptop', 'Can check duplicate uptop post', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (22, 'Post.Create', 'Can create post', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (23, 'Post.Create.Uptop', 'Can create uptop post', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (24, 'Post.Delete', 'Can delete post', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (25, 'Post.Get.Uptop', 'Can get uptop post', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (26, 'Post.Update', 'Can update post', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (27, 'Post.View.All.Personal', 'Can view all personal post', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (28, 'PostStatistic.View.Detail.In.Date', 'Can view post statistic detail in date', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (29, 'PostStatistic.View.In.Date.Range', 'Can view post statistic in date range', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (30, 'PostStatistic.View.Top.In.Date', 'Can view top post statistic in date', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (31, 'Review.Check.Can.Review', 'Can check can review', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (32, 'Review.Create', 'Can create review', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (33, 'Role.Create', 'Can create a role', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (34, 'Role.Update', 'Can update a role', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (35, 'Role.View.All', 'Can view all role', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (36, 'Role.View.One', 'Can view a role detail', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (37, 'User.Update.Account.Access', 'Can update user account access in system', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (38, 'User.Update.Profile', 'Can update user profile', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (39, 'User.View.Account.Access', 'Can view user account access in system', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (40, 'User.View.All', 'Can view all users in system', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (41, 'User.View.Personal', 'Can view personal user profile', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (42, 'UserStatistic.View.Detail.In.Date', 'Can view user statistic detail in date', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (43, 'UserStatistic.View.In.Date.Range', 'Can view user statistic in date range', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (44, 'UserStatistic.View.Top.In.Date', 'Can view top user statistic in date', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (45, 'VNP.Create.Payment', 'Can create vnp payment', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (46, 'VNP.View.All.History', 'Can view all vnp history in system', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (47, 'VNP.View.All.History.Personal', 'Can view personal vnp history', 1, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (48, 'Booking.Approve.Meeting', 'Can approve meeting', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (49, 'Booking.Confirm.Met', 'Can confirm guest met motel', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (50, 'Booking.View.All.Personal', 'Can view all meeting of host', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (51, 'ConfigSetting.View.One', 'Can view one config setting', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (52, 'FreeTime.Create', 'Can create free time', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (53, 'FreeTime.View.All', 'Can view all free time', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (54, 'Notification.Update', 'Can update notification', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (55, 'Notification.View.All', 'Can view all notification', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (56, 'Payment.View.All.History.Personal', 'Can view personal payment history', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (57, 'Post.Check.Duplicate.Uptop', 'Can check duplicate uptop post', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (58, 'Post.Create', 'Can create post', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (59, 'Post.Create.Uptop', 'Can create uptop post', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (60, 'Post.Delete', 'Can delete post', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (61, 'Post.Get.Uptop', 'Can get uptop post', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (62, 'Post.Update', 'Can update post', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (63, 'Post.View.All.Personal', 'Can view all personal post', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (64, 'PostStatistic.View.Detail.In.Date', 'Can view post statistic detail in date', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (65, 'PostStatistic.View.In.Date.Range', 'Can view post statistic in date range', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (66, 'PostStatistic.View.Top.In.Date', 'Can view top post statistic in date', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (67, 'User.Update.Profile', 'Can update user profile', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (68, 'User.View.Personal', 'Can view personal user profile', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (69, 'VNP.Create.Payment', 'Can create vnp payment', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (70, 'VNP.View.All.History.Personal', 'Can view personal vnp history', 2, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (71, 'Booking.Create.Meeting', 'Can create meeting', 3, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (72, 'Booking.View.All.Booked', 'Can view all meeting of guest', 3, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (73, 'Bookmark.Create', 'Can create a bookmark', 3, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (74, 'Bookmark.Remove', 'Can remove a bookmark', 3, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (75, 'Bookmark.View', 'Can view bookmarked post', 3, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (76, 'FreeTime.View.All', 'Can view all free time', 3, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (77, 'Notification.Update', 'Can update notification', 3, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (78, 'Notification.View.All', 'Can view all notification', 3, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (79, 'Review.Check.Can.Review', 'Can check can review', 3, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (80, 'Review.Create', 'Can create review', 3, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (81, 'User.View.Personal', 'Can view personal user profile', 3, NOW());
INSERT INTO `permission` (`id`, `key`, `description`, `role_id`, `created_at`) VALUES (82, 'User.Update.Profile', 'Can update user profile', 3, NOW());
